spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  websocket:
    stomp:
      enabled: true
  application:
    name: learning_api
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI}
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    default-encoding: UTF-8
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    verify:
      host: http://localhost:8080
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: -1
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.[enable.idempotence]: true
      properties.[max.in.flight.requests.per.connection]: 5
    consumer:
      bootstrap-servers: localhost:9094
      group-id: group-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.learning_api.kafka.message
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
security:
  jwt:
    accessTokenKey: YourAccessTokenKey
    refreshTokenKey: YourRefreshTokenKey
cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

server:
  port: 8080

google:
  api:
    key: ${GOOGLE_API_KEY}
payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}

client:
  url:
    payment-status: "https://www.facebook.com"